
INSERT INTO `tblplatos` (`idPlatos`, `Nombre`, `Tipo`, `grupoProducto`) VALUES
(8, 'CHICHARON DE CERDO', 'Segundos', 'PLATO ESPECIAL'),
(9, 'ENSALDA DE ESPARRAGOS', 'Entrada', 'ALMUERZO VEGETARIANO'),
(10, 'ENSALDA DE SARDINA', 'Entrada', 'ALMUERZO TRADICIONAL'),
(11, 'SOPA DE VERDURAS', 'Sopas', 'ALMUERZO VEGETARIANO'),
(12, 'SOPA ANGELICAL', 'Sopas', 'ALMUERZO TRADICIONAL'),
(13, 'SOPA DE ESPARRAGOS', 'Sopas', 'ALMUERZO VEGETARIANO'),
(14, 'SOPA DE SEMOLA CON PAPAS', 'Sopas', 'ALMUERZO TRADICIONAL'),
(15, 'MILANESA DE POLLO', 'Segundos', 'ALMUERZO TRADICIONAL'),
(16, 'REVUELTO', 'Segundos', 'ALMUERZO TRADICIONAL'),
(17, 'CUPIS DE TRIGO', 'Segundos', 'ALMUERZO VEGETARIANO'),
(18, 'ALBONDIGAS VEGANAS', 'Segundos', 'ALMUERZO VEGETARIANO'),
(19, 'GELATINA', 'Postre', 'ALMUERZO TRADICIONAL'),
(20, 'COMPOTA DE PIÑA', 'Postre', 'ALMUERZO TRADICIONAL'),
(21, 'FLAN DE CHOCOLATE', 'Postre', 'ALMUERZO TRADICIONAL'),
(22, 'FLAN DE CHOCOLATE', 'Postre', 'ALMUERZO VEGETARIANO'),
(23, 'EMPANADA DE QUESO', 'Postre', 'ALMUERZO VEGETARIANO'),
(24, 'GELATINA DE PATA', 'Postre', 'ALMUERZO VEGETARIANO'),
(25, 'ENSALDA DE FRIAMBRE', 'Entrada', 'ALMUERZO TRADICIONAL');

